Bump actionlint from 1.7.1 to 1.7.6 (#3)

diff --git a/.github/workflows/functional-tests.yml b/.github/workflows/functional-tests.yml
--- a/.github/workflows/functional-tests.yml
+++ b/.github/workflows/functional-tests.yml
@@ -4,39 +4,106 @@ name: Functional Tests
 on: # yamllint disable-line rule:truthy
   pull_request:
     paths:
-      - "action.yml"
-      - ".github/workflows/functional-tests.yml"
+      - .github/workflows/functional-tests.yml
+      - src/**
+      - action.yml
   push:
     branches:
-      - "main"
+      - main
+  schedule:
+    # Every Friday at 09:00 JST
+    - cron: "0 0 * * 5"
+  workflow_dispatch: {}
 
 defaults:
   run:
     shell: sh
 
 jobs:
-  run-script:
-    name: Run script
+  setup-groff:
+    name: Setup groff
+    runs-on: ${{ matrix.os }}-latest
     timeout-minutes: 5
     strategy:
       fail-fast: false
       matrix:
-        os: ["ubuntu", "macos", "windows"]
-    runs-on: ${{ matrix.os }}-latest
+        os: ["macos"]
     steps:
       - name: Checkout ${{ github.repository }}
         uses: actions/checkout@v4
       - name: Setup groff
         id: setup-groff
-        continue-on-error: ${{ matrix.os == 'windows' }}
         uses: ./
-      - name: Run script
-        if: matrix.os != 'windows'
-        run: groff -man -Tascii ./hello-world.roff
-      - name: Expect the previous step to fail
-        if: matrix.os == 'windows'
+      - name: Test action completion
         run: |
-          if [ "${{ steps.setup-groff.outcome }}" != "failure" ]; then
-            echo "::error::Previous step should have failed but didn't"
-            exit 1
-          fi
+          test_equal() {
+            if [ "${2}" != "${3}" ]; then
+              echo "::error title=${1}::Expected: ${3}. Actual: ${2}."
+              exit 1
+            fi
+          }
+          test_equal "groff should be installed" \
+            "${{ steps.setup-groff.outputs.installed }}" \
+            "true"
+      - name: Run script
+        run: groff -man -Tascii ./hello-world.roff
+
+  setup-groff-in-container:
+    name: Setup groff in container (ubuntu)
+    runs-on: ubuntu-latest
+    timeout-minutes: 5
+    container:
+      image: ubuntu:25.04
+    steps:
+      - name: Checkout ${{ github.repository }}
+        uses: actions/checkout@v4
+      - name: Setup groff
+        id: setup-groff
+        uses: ./
+      - name: Test action completion
+        run: |
+          test_equal() {
+            if [ "${2}" != "${3}" ]; then
+              echo "::error title=${1}::Expected: ${3}. Actual: ${2}."
+              exit 1
+            fi
+          }
+          test_equal "groff should be installed" \
+            "${{ steps.setup-groff.outputs.installed }}" \
+            "true"
+      - name: Run script
+        run: groff -man -Tascii ./hello-world.roff
+
+  test-force:
+    name: Test force
+    runs-on: macos-latest
+    timeout-minutes: 5
+    strategy:
+      fail-fast: false
+      matrix:
+        force: ["true", "false"]
+    steps:
+      - name: Checkout ${{ github.repository }}
+        uses: actions/checkout@v4
+      - name: Setup groff 1
+        id: setup-groff-1
+        uses: ./
+      - name: Setup groff 2
+        id: setup-groff-2
+        uses: ./
+        with:
+          force: ${{ matrix.force }}
+      - name: Test action completion
+        run: |
+          test_equal() {
+            if [ "${2}" != "${3}" ]; then
+              echo "::error title=${1}::Expected: ${3}. Actual: ${2}."
+              exit 1
+            fi
+          }
+          test_equal "Wrong \"installed\" output from setup-groff-1" \
+            "${{ steps.setup-groff-1.outputs.installed }}" \
+            "true"
+          test_equal "Wrong \"installed\" output from setup-groff-2" \
+            "${{ steps.setup-groff-2.outputs.installed }}" \
+            "${{ matrix.force }}"
diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -5,33 +5,47 @@ description: "This action sets up groff (GNU roff)."
 branding:
   icon: terminal
   color: gray-dark
+inputs:
+  force:
+    description: |
+      If "false" skips installation if groff is already installed. If "true"
+      installs groff in any case. Defaults to "false".
+    required: false
+    default: "false"
+outputs:
+  installed:
+    description: Whether groff was installed or not.
+    value: "${{ steps.install-groff.outcome == 'success' }}"
 runs:
   using: "composite"
   steps:
     - name: Fail
       if: ${{ runner.os == 'Windows' }}
-      run: echo "::error::${RUNNER_OS} ${RUNNER_ARCH} is not supported" && exit 1
+      run: |
+        echo "::error title=OS is not supported::${RUNNER_OS} ${RUNNER_ARCH} is not supported"
+        exit 1
       shell: sh
+
     - name: Collect info
       id: info
-      run: |
-        installed=$(if command -v groff >/dev/null 2>&1; then echo true; else echo false; fi)
-        echo "installed=${installed}" >> "$GITHUB_OUTPUT"
+      env:
+        INPUT_FORCE: "${{ inputs.force }}"
+      run: ./collect-info.sh "${INPUT_FORCE}"
       shell: sh
-    - name: Install groff (Linux)
-      if: ${{ steps.info.outputs.installed == 'false' && runner.os == 'Linux' }}
+      working-directory: "${{ github.action_path }}/src"
+
+    - name: Install groff
+      if: ${{ steps.info.outputs.bin-installed == 'false' }}
+      id: install-groff
       run: |
-        apt-get update
-        apt-get install groff -y
-      shell: sh
-    - name: Install groff (macOS)
-      if: ${{ steps.info.outputs.installed == 'false' && runner.os == 'macOS' }}
-      run: |
-        if ! command -v brew >/dev/null 2>&1; then
-          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+        if [ "$RUNNER_OS" = "Linux" ]; then
+          apt-get update
+          apt-get install groff -y
+        else
+          brew install groff
         fi
-        brew install groff
       shell: sh
-    - name: Print groff version
+
+    - name: Print version
       run: groff --version
       shell: sh
