Improve tests

diff --git a/.github/workflows/functional-tests.yml b/.github/workflows/functional-tests.yml
--- a/.github/workflows/functional-tests.yml
+++ b/.github/workflows/functional-tests.yml
@@ -20,8 +20,8 @@ defaults:
     shell: sh
 
 jobs:
-  run-script:
-    name: Run script
+  setup-groff:
+    name: Setup groff
     timeout-minutes: 5
     strategy:
       fail-fast: false
@@ -32,6 +32,52 @@ jobs:
       - name: Checkout ${{ github.repository }}
         uses: actions/checkout@v4
       - name: Setup groff
+        id: setup-groff
         uses: ./
+      - name: Test action completion
+        if: ${{ matrix.os != 'Windows' }}
+        run: |
+          test_equal() {
+            if [ "${2}" != "${3}" ]; then
+              echo "::error title=${1}::Expected: ${3}. Actual: ${2}."
+              exit 1
+            fi
+          }
+          test_equal "groff should be installed" \
+            "${{ steps.setup-groff.outputs.installed }}" \
+            "true"
       - name: Run script
         run: groff -man -Tascii ./hello-world.roff
+  test-force:
+    name: Test force
+    runs-on: ubuntu-latest
+    timeout-minutes: 5
+    strategy:
+      fail-fast: false
+      matrix:
+        force: ["true", "false"]
+    steps:
+      - name: Checkout ${{ github.repository }}
+        uses: actions/checkout@v4
+      - name: Setup groff 1
+        id: setup-groff-1
+        uses: ./
+      - name: Setup groff 2
+        id: setup-groff-2
+        uses: ./
+        with:
+          force: ${{ matrix.force }}
+      - name: Test action completion
+        run: |
+          test_equal() {
+            if [ "${2}" != "${3}" ]; then
+              echo "::error title=${1}::Expected: ${3}. Actual: ${2}."
+              exit 1
+            fi
+          }
+          test_equal "Wrong \"installed\" output from setup-groff-1" \
+            "${{ steps.setup-groff-1.outputs.installed }}" \
+            "true"
+          test_equal "Wrong \"installed\" output from setup-groff-2" \
+            "${{ steps.setup-groff-2.outputs.installed }}" \
+            "${{ matrix.force }}"
